### PR TITLE
new time range

### PR DESCRIPTION
**Pull request by DavidDoukhan**
Hi,

I've added holidays dates starting from 1990.
I saw few differences between my data and your data for the period 2008-2020.

I checked manually all differences using a governmental source: http://www.education.gouv.fr/cid197/les-archives-calendrier-scolaire-partir-1960.html

Hoping this will help!

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Thanks a lot @DavidDoukhan! I'll take a look at this PR next week.

**Comment by DavidDoukhan** [comment]
> Thanks a lot @DavidDoukhan! I'll take a look at this PR next week.

Hi @AntoineAugusti  !

I've got a last remark concerning one of the biggest difference between our data, observed for 2016 spring holidays, which is in my point of view quite tricky.
According to my data, these holidays occur from 2016-04-03 to 2016-05-01.
According to your data, these holidays occur from 2016-04-09 to 2016-05-08 .

The point is that these differences can also be observed in contradictory governmental sources.

These sources correspond to my data:
https://vacances-scolaires.education/annee-2015-2016.php
http://cache.media.education.gouv.fr/file/Services/17/1/calendrierscolaire20152016_296171.pdf
https://www.lemonde.fr/bac-lycee/article/2015/09/01/vacances-scolaires-2015-2016-le-calendrier-officiel_4742656_4401499.html

This source correspond to your data:
http://cache.media.education.gouv.fr/file/Services/17/8/calendrierscolaire2014a2017_296178.pdf

As long as I'm not concerned with school holidays, I believe the source I used are more accurate, since they are matching with many press articles telling about holidays.

Hoping this will help!

**Comment by AntoineAugusti** [comment]
Thanks a million for your work @DavidDoukhan! It's super appreciated 👍 

It's super weird for these spring holidays in 2016 😨 I checked and service-public.fr says you're right and the article is from March 2016. https://www.service-public.fr/particuliers/actualites/A10473

**Comment by AntoineAugusti** [comment]
I've also released a new version of the Python package https://github.com/AntoineAugusti/vacances-scolaires-france and updated the documentation of the dataset on data.gouv.fr

**Pull request merged**
